import { logger, db, error } from '@gnar-engine/core';
import { v4 as uuidv4 } from 'uuid';

/**
 * Password Reset Service
 */
export const passwordReset = {

    /**
     * Create a password reset token
     */
    createResetToken: async ({ email }) => {
        if (!email) {
            throw new error.badRequest('Email is required');
        }

        const token = uuidv4();

        try {
            // Optional: allow only one active token per email
            await db.query(
                'DELETE FROM password_resets WHERE email = ?',
                [email]
            );

            // IMPORTANT: expires_at is GENERATED in DB — do NOT insert it
            await db.query(
                'INSERT INTO password_resets (token, email) VALUES (?, ?)',
                [token, email]
            );

            return token;
        } catch (err) {
            logger.error({ err }, 'Failed to create password reset token');
            throw err;
        }
    },

    /**
     * Verify a password reset token
     */
    verifyPasswordResetToken: async ({ token, email }) => {
        if (!token || !email) return false;

        try {
            const [rows] = await db.query(
                `
                SELECT token, expires_at
                FROM password_resets
                WHERE token = ? AND email = ?
                LIMIT 1
                `,
                [token, email]
            );

            if (!rows || rows.length === 0) {
                return false;
            }

            const record = rows[0];

            // expires_at is generated by DB
            if (new Date(record.expires_at) < new Date()) {
                return false;
            }

            return true;
        } catch (err) {
            logger.error({ err }, 'Failed to verify password reset token');
            throw err;
        }
    },

    /**
     * Consume token after successful password change
     */
    consumeToken: async ({ token, email }) => {
        if (!token || !email) return;

        try {
            await db.query(
                'DELETE FROM password_resets WHERE token = ? AND email = ?',
                [token, email]
            );
        } catch (err) {
            logger.error({ err }, 'Failed to consume password reset token');
            throw err;
        }
    },
};